### ISSUE TITLE
Web Browser won't open

### ISSUE THREAD

**Issue by educampos28** [meshtastic/Meshtastic-gui-installer#226]
After updating my Heltec module to 1.2.65.0adc5ce, the web page doesn't open and returns the following error message

Something went wrong:
a.map is not a function
Try again
